baseurl = "/"
languageCode = "en-us"
title = "STATS 220 Data Technology"
theme = "hugo-cards"
paginate = 12

staticDir = ["static", "lectures"]

[params]
  custom_css = ["css/wang.css"]

  builtBy = "netlify"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "https://github.com/STATS-UOA/stats220"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "The University of Auckland"
     link = "http://auckland.ac.nz"
